name: Push Docker to AliyunACR

on:
  workflow_dispatch:
    inputs:
      image_url:
        description: 'DockerHub Image URL'
        required: true
        default: 'username/image:tag'

      repository_name:
        description: '在阿里云镜像中的名称 例:public-cdn/{名称} ，默认为空读取image_url中名称'
        required: false  # Make it optional
        default: ''

jobs:
  build:
    name: Pull and Push to Aliyun
    runs-on: ubuntu-latest
    env:
      ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"
      ALIYUN_NAME_SPACE: "${{ secrets.ALIYUN_NAME_SPACE }}"
      ALIYUN_REGISTRY_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
      ALIYUN_REGISTRY_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"
    steps:
    - name: Set Default Repository Name
      run: |
        if [[ "${{ github.event.inputs.repository_name }}" == "" ]]; then
          export REPOSITORY_NAME=$(echo "${{ github.event.inputs.image_url }}" | awk -F '/' '{print $NF}' | cut -d ':' -f 1)
        else
          export REPOSITORY_NAME="${{ github.event.inputs.repository_name }}"
        fi
        echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $GITHUB_ENV

    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 2048
        swap-size-mb: 128
        remove-dotnet: 'true'
        remove-haskell: 'true'
        build-mount-path: '/var/lib/docker/'

    - name: Restart docker
      run: sudo service docker restart

    - name: Free up disk space complete
      run: |
        echo "Free up disk space complete"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push image to Aliyun
      run: |
        docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
        image_url="${{ github.event.inputs.image_url }}"
        docker pull $image_url
        
        platform=$(echo "$image_url" | awk -F'--platform[ =]' '{if (NF>1) print $2}' | awk '{print $1}')
        platform_prefix="${platform:+${platform//\//_}_}"
        image_name_tag=$(basename "$image_url" | sed 's/@.*//' | sed 's/:/_/g')

        name_space=$(echo "$image_url" | awk -F'/' '{if (NF==3) print $2; else if (NF==2) print $1}')
        name_space_prefix="${name_space:+${name_space}_}"
        
        echo "platform_prefix: ${platform_prefix}"
        echo "name_space_prefix: ${name_space_prefix}"
        echo "image_name_tag: ${image_name_tag}"
        
        new_image="$ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/$platform_prefix$name_space_prefix$image_name_tag"
        
        echo "docker tag $image_url $new_image"
        docker tag $image_url $new_image
        echo "docker push $new_image"
        docker push $new_image
        docker rmi $image_url $new_image
